---

- hosts: all
  remote_user: vagrant
  become: yes
  roles:
    - locust

- hosts: locust-master
  remote_user: vagrant
  become: yes
  vars:
    locust_role: master
  roles:
    - locust_test

- hosts: locust-slave
  remote_user: vagrant
  become: yes
  vars:
    locust_role: slave
  roles:
    - locust_test
