
---

- name: LOCUST | Create local directory to copy sources
  file:
    path: /opt/locust
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755

- name: LOCUST | Install prerequisites
  package:
    name:
      - git
      - python-pip
      - gcc
      - jq
      - python2.7
      - python2.7-dev
      - musl-dev
      - g++
      - curl
      - bc
      - gnuplot
      - ttf-dejavu
    state: present

- name: LOCUST | Installation
  pip:
    name:
      - locustio
      - pyzmq
      - faker
    state: present
