---

- name: LOCUST TEST | Deploy a simple python test script
  copy:
    src: opt/locust/example.py
    dest: /opt/locust/example.py
    owner: root
    group: root
    mode: 0644

- name: LOCUST TEST | Run Locust test on master node
  shell: nohup locust -f /opt/locust/example.py --master --host=http://example.com &
  when: inventory_hostname in groups['locust-master']

- name: LOCUST TEST | Run Locust test on slave nodes
  shell: nohup locust -f /opt/locust/example.py --slave --master-host={{ hostvars[groups['locust-master'][0]].ip }} --host=http://example.com &
  when: inventory_hostname in groups['locust-slave']
